apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: openshift-operators 
  labels:
    operators.coreos.com/cert-manager.openshift-operators: ''
spec:
  channel: stable 
  name: cert-manager 
  source: community-operators 
  sourceNamespace: openshift-marketplace 
  installPlanApproval: Automatic
