---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: apps-wildcard-cert-tls