apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-utils-operator
  namespace: cert-utils-operator
  labels:
    operators.coreos.com/cert-utils-operator.cert-utils-operator: ''
spec:
  channel: alpha
  name: cert-utils-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
